Ethereum: deploy with forge (#3862)
* eth: deploy with forge

* Delete unused scripts

* Support upgrade, bytecode verify and publish tool

* Add script to register all chains on a new chain

diff --git a/ethereum/verify b/ethereum/verify
--- a/ethereum/verify
+++ b/ethereum/verify
@@ -1,7 +1,5 @@
 #!/bin/bash
 
-set -euo pipefail
-
 function usage() {
 cat <<EOF >&2
 Usage:
@@ -48,6 +46,16 @@ shift $((OPTIND - 1))
 json_file=$1
 contract_addr=$2
 
+# See if they specified the forge output. Do this before we set the error handling flags because
+# this pipeline will intentionally fail if they are using the truffle build output.
+use_forge=""
+echo "$json_file" | grep "build-forge" > /dev/null
+if [[ $? -eq 0 ]]; then
+  use_forge="true"
+fi
+
+set -euo pipefail
+
 # network and rpc flags are mutually exlusive
 [[ -n $network && -n $rpc ]] && usage
 
@@ -71,7 +79,11 @@ fi
 deployed=$(mktemp)
 local=$(mktemp)
 
-cat "$json_file" | jq -r .deployedBytecode > "$local"
+if [[ -z $use_forge ]]; then
+  cat "$json_file" | jq -r .deployedBytecode > "$local"
+else
+  cat "$json_file" | jq -r .deployedBytecode | jq -r .object > "$local"  
+fi
 
 ret=0
 # Grab bytecode from the JSON RPC using the eth_getCode method.
